version: '3.8'

services:
  db:
    image: postgres:15
    container_name: tokiomarine_db
    environment:
      POSTGRES_DB: tokiomarine
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./api
    container_name: tokiomarine_backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/tokiomarine
      SPRING_DATASOURCE_USERNAME: docker
      SPRING_DATASOURCE_PASSWORD: docker
      JWT_SECRET: tokiomarine-test
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    container_name: tokiomarine_frontend
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  postgres_data:
